.TH LIBCRYTWI 3 2026-05-04 "crytwi-py 0.0.1-alpha"
.SH NAME
libcrytwi \- A secure file encryption library
.SH LIBRARY
Crytwi project, written in Python
.RI ( libcrytwi )
.SH SYNOPSIS
.nf
.BI "import "libcrytwi
.P
.BI libcrytwi.assemble_fixed_meta_header(
.BI 	manage_flag: int = 0x00,
.BI 	cipher_type: int = 0x00,
.BI 	endian_flag: int = 0x00,
.BI 	entropies: tuple = (),
.BI 	kdf_params: tuple = (),
.BI 	max_chunk_size: int = (64 * 1024),
.BI 	payload_len: int = 0
.B ) -> bytes
.BI libcrytwi.assemble_dynamic_meta_header(
.BI 	manage_flag: int = 0x00,
.BI 	non_encrypt_meta_infos: tuple = (),
.BI 	kdf_key: bytes = b'',
.BI 	iv_seed: bytes = b'',
.B ) -> bytes
.BI extract_meta_header(
.BI 	file: BinaryIO,
.BI 	offset: int = 0
.B ) -> CrytwiFixedMetaHeader | int
.fi
.SH DESCRIPTION

.SH SEE ALSO
