.TH LIBCRYTWI.ASSEMBLE_FIXED_META_HEADER 3 2026-05-04 "crytwi-py 0.0.1-alpha"
.SH NAME
assemble_fixed_meta_header \- Assemble the fixed header
.SH LIBRARY
Crytwi project, written in Python
.RI ( libcrytwi )
.SH SYNOPSIS
.nf
.B import libcrytwi
.PP
.BI ret\ =\ libcrytwi.assemble_fixed_meta_header(
.BI		manage_flag: int = 0x00,
.BI		cipher_type: int = 0x00,
.BI		endian_flag: int = 0x00,
.BI		entropies: tuple = (),
.BI		kdf_params: tuple = (),
.BI		max_chunk_size: int = (64 * 1024),
.BI		payload_len: int = 0
.BI )
.fi
.SH DESCRIPTION

.SH RETURN VALUE

.SH ERRORS

.SH ATTRIBUTES

.SH CAVEATS

.SH BUGS

.SH SEE ALSO
.BR libcrytwi (3),
